import { Instance } from "mobx-state-tree"
import { AddFavoritePayloadModelBase } from "./AddFavoritePayloadModel.base"

/* The TypeScript type of an instance of AddFavoritePayloadModel */
export interface AddFavoritePayloadModelType extends Instance<typeof AddFavoritePayloadModel.Type> {}

/* A graphql query fragment builders for AddFavoritePayloadModel */
export { selectFromAddFavoritePayload, addFavoritePayloadModelPrimitives, AddFavoritePayloadModelSelector } from "./AddFavoritePayloadModel.base"

/**
 * AddFavoritePayloadModel
 *
 * Autogenerated return type of AddFavorite
 */
export const AddFavoritePayloadModel = AddFavoritePayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
