import { Instance } from "mobx-state-tree"
import { AddSubAccountPayloadModelBase } from "./AddSubAccountPayloadModel.base"

/* The TypeScript type of an instance of AddSubAccountPayloadModel */
export interface AddSubAccountPayloadModelType extends Instance<typeof AddSubAccountPayloadModel.Type> {}

/* A graphql query fragment builders for AddSubAccountPayloadModel */
export { selectFromAddSubAccountPayload, addSubAccountPayloadModelPrimitives, AddSubAccountPayloadModelSelector } from "./AddSubAccountPayloadModel.base"

/**
 * AddSubAccountPayloadModel
 *
 * Autogenerated return type of AddSubAccount
 */
export const AddSubAccountPayloadModel = AddSubAccountPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
