import { Instance } from "mobx-state-tree"
import { DeactivatePayloadModelBase } from "./DeactivatePayloadModel.base"

/* The TypeScript type of an instance of DeactivatePayloadModel */
export interface DeactivatePayloadModelType extends Instance<typeof DeactivatePayloadModel.Type> {}

/* A graphql query fragment builders for DeactivatePayloadModel */
export { selectFromDeactivatePayload, deactivatePayloadModelPrimitives, DeactivatePayloadModelSelector } from "./DeactivatePayloadModel.base"

/**
 * DeactivatePayloadModel
 *
 * Autogenerated return type of Deactivate
 */
export const DeactivatePayloadModel = DeactivatePayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
