import { Instance } from "mobx-state-tree"
import { IsEnterprisePayloadModelBase } from "./IsEnterprisePayloadModel.base"

/* The TypeScript type of an instance of IsEnterprisePayloadModel */
export interface IsEnterprisePayloadModelType extends Instance<typeof IsEnterprisePayloadModel.Type> {}

/* A graphql query fragment builders for IsEnterprisePayloadModel */
export { selectFromIsEnterprisePayload, isEnterprisePayloadModelPrimitives, IsEnterprisePayloadModelSelector } from "./IsEnterprisePayloadModel.base"

/**
 * IsEnterprisePayloadModel
 *
 * Autogenerated return type of IsEnterprise
 */
export const IsEnterprisePayloadModel = IsEnterprisePayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
