import { Instance } from "mobx-state-tree"
import { LoginPayloadModelBase } from "./LoginPayloadModel.base"

/* The TypeScript type of an instance of LoginPayloadModel */
export interface LoginPayloadModelType extends Instance<typeof LoginPayloadModel.Type> {}

/* A graphql query fragment builders for LoginPayloadModel */
export { selectFromLoginPayload, loginPayloadModelPrimitives, LoginPayloadModelSelector } from "./LoginPayloadModel.base"

/**
 * LoginPayloadModel
 *
 * Autogenerated return type of Login
 */
export const LoginPayloadModel = LoginPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
