import { Instance } from "mobx-state-tree"
import { LogoutPayloadModelBase } from "./LogoutPayloadModel.base"

/* The TypeScript type of an instance of LogoutPayloadModel */
export interface LogoutPayloadModelType extends Instance<typeof LogoutPayloadModel.Type> {}

/* A graphql query fragment builders for LogoutPayloadModel */
export { selectFromLogoutPayload, logoutPayloadModelPrimitives, LogoutPayloadModelSelector } from "./LogoutPayloadModel.base"

/**
 * LogoutPayloadModel
 *
 * Autogenerated return type of Logout
 */
export const LogoutPayloadModel = LogoutPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
