import { Instance } from "mobx-state-tree"
import { RedeemPayloadModelBase } from "./RedeemPayloadModel.base"

/* The TypeScript type of an instance of RedeemPayloadModel */
export interface RedeemPayloadModelType extends Instance<typeof RedeemPayloadModel.Type> {}

/* A graphql query fragment builders for RedeemPayloadModel */
export { selectFromRedeemPayload, redeemPayloadModelPrimitives, RedeemPayloadModelSelector } from "./RedeemPayloadModel.base"

/**
 * RedeemPayloadModel
 *
 * Autogenerated return type of Redeem
 */
export const RedeemPayloadModel = RedeemPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
