/* This is a mst-gql generated file, don't modify it manually */
/* eslint-disable */
/* tslint:disable */

import { types } from "mobx-state-tree"
import { QueryBuilder } from "mst-gql"
import { ModelBase } from "./ModelBase"
import { RedemptionModel, RedemptionModelType } from "./RedemptionModel"
import { RedemptionModelSelector } from "./RedemptionModel.base"
import { RootStoreType } from "./index"


/**
 * RedeemWithRegistrationFormPayloadBase
 * auto generated base class for the model RedeemWithRegistrationFormPayloadModel.
 *
 * Autogenerated return type of RedeemWithRegistrationForm
 */
export const RedeemWithRegistrationFormPayloadModelBase = ModelBase
  .named('RedeemWithRegistrationFormPayload')
  .props({
    __typename: types.optional(types.literal("RedeemWithRegistrationFormPayload"), "RedeemWithRegistrationFormPayload"),
    /** A unique identifier for the client performing the mutation. */
    clientMutationId: types.union(types.undefined, types.null, types.string),
    message: types.union(types.undefined, types.null, types.string),
    redemption: types.union(types.undefined, types.null, types.late((): any => RedemptionModel)),
  })
  .views(self => ({
    get store() {
      return self.__getStore<RootStoreType>()
    }
  }))

export class RedeemWithRegistrationFormPayloadModelSelector extends QueryBuilder {
  get clientMutationId() { return this.__attr(`clientMutationId`) }
  get message() { return this.__attr(`message`) }
  redemption(builder?: string | RedemptionModelSelector | ((selector: RedemptionModelSelector) => RedemptionModelSelector)) { return this.__child(`redemption`, RedemptionModelSelector, builder) }
}
export function selectFromRedeemWithRegistrationFormPayload() {
  return new RedeemWithRegistrationFormPayloadModelSelector()
}

export const redeemWithRegistrationFormPayloadModelPrimitives = selectFromRedeemWithRegistrationFormPayload().clientMutationId.message
