import { Instance } from "mobx-state-tree"
import { RemoveSubAccountPayloadModelBase } from "./RemoveSubAccountPayloadModel.base"

/* The TypeScript type of an instance of RemoveSubAccountPayloadModel */
export interface RemoveSubAccountPayloadModelType extends Instance<typeof RemoveSubAccountPayloadModel.Type> {}

/* A graphql query fragment builders for RemoveSubAccountPayloadModel */
export { selectFromRemoveSubAccountPayload, removeSubAccountPayloadModelPrimitives, RemoveSubAccountPayloadModelSelector } from "./RemoveSubAccountPayloadModel.base"

/**
 * RemoveSubAccountPayloadModel
 *
 * Autogenerated return type of RemoveSubAccount
 */
export const RemoveSubAccountPayloadModel = RemoveSubAccountPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
