import { Instance } from "mobx-state-tree"
import { ResetPasswordPayloadModelBase } from "./ResetPasswordPayloadModel.base"

/* The TypeScript type of an instance of ResetPasswordPayloadModel */
export interface ResetPasswordPayloadModelType extends Instance<typeof ResetPasswordPayloadModel.Type> {}

/* A graphql query fragment builders for ResetPasswordPayloadModel */
export { selectFromResetPasswordPayload, resetPasswordPayloadModelPrimitives, ResetPasswordPayloadModelSelector } from "./ResetPasswordPayloadModel.base"

/**
 * ResetPasswordPayloadModel
 *
 * Autogenerated return type of ResetPassword
 */
export const ResetPasswordPayloadModel = ResetPasswordPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
