import { Instance } from "mobx-state-tree"
import { SelectMembershipPlanPayloadModelBase } from "./SelectMembershipPlanPayloadModel.base"

/* The TypeScript type of an instance of SelectMembershipPlanPayloadModel */
export interface SelectMembershipPlanPayloadModelType extends Instance<typeof SelectMembershipPlanPayloadModel.Type> {}

/* A graphql query fragment builders for SelectMembershipPlanPayloadModel */
export { selectFromSelectMembershipPlanPayload, selectMembershipPlanPayloadModelPrimitives, SelectMembershipPlanPayloadModelSelector } from "./SelectMembershipPlanPayloadModel.base"

/**
 * SelectMembershipPlanPayloadModel
 *
 * Autogenerated return type of SelectMembershipPlan
 */
export const SelectMembershipPlanPayloadModel = SelectMembershipPlanPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
