/* This is a mst-gql generated file, don't modify it manually */
/* eslint-disable */
/* tslint:disable */

import { types } from "mobx-state-tree"
import { QueryBuilder } from "mst-gql"
import { ModelBase } from "./ModelBase"
import { RootStoreType } from "./index"


/**
 * UpdateOnboardingStepPayloadBase
 * auto generated base class for the model UpdateOnboardingStepPayloadModel.
 *
 * Autogenerated return type of UpdateOnboardingStep
 */
export const UpdateOnboardingStepPayloadModelBase = ModelBase
  .named('UpdateOnboardingStepPayload')
  .props({
    __typename: types.optional(types.literal("UpdateOnboardingStepPayload"), "UpdateOnboardingStepPayload"),
    /** A unique identifier for the client performing the mutation. */
    clientMutationId: types.union(types.undefined, types.null, types.string),
    message: types.union(types.undefined, types.null, types.string),
    nextStep: types.union(types.undefined, types.null, types.string),
    nextStepNumber: types.union(types.undefined, types.null, types.integer),
  })
  .views(self => ({
    get store() {
      return self.__getStore<RootStoreType>()
    }
  }))

export class UpdateOnboardingStepPayloadModelSelector extends QueryBuilder {
  get clientMutationId() { return this.__attr(`clientMutationId`) }
  get message() { return this.__attr(`message`) }
  get nextStep() { return this.__attr(`nextStep`) }
  get nextStepNumber() { return this.__attr(`nextStepNumber`) }
}
export function selectFromUpdateOnboardingStepPayload() {
  return new UpdateOnboardingStepPayloadModelSelector()
}

export const updateOnboardingStepPayloadModelPrimitives = selectFromUpdateOnboardingStepPayload().clientMutationId.message.nextStep.nextStepNumber
