/* This is a mst-gql generated file, don't modify it manually */
/* eslint-disable */
/* tslint:disable */

import { types } from "mobx-state-tree"
import { QueryBuilder } from "mst-gql"
import { ModelBase } from "./ModelBase"
import { UserModel, UserModelType } from "./UserModel"
import { UserModelSelector } from "./UserModel.base"
import { RootStoreType } from "./index"


/**
 * UpdateCreditCardPayloadBase
 * auto generated base class for the model UpdateCreditCardPayloadModel.
 *
 * Autogenerated return type of UpdateCreditCard
 */
export const UpdateCreditCardPayloadModelBase = ModelBase
  .named('UpdateCreditCardPayload')
  .props({
    __typename: types.optional(types.literal("UpdateCreditCardPayload"), "UpdateCreditCardPayload"),
    /** A unique identifier for the client performing the mutation. */
    clientMutationId: types.union(types.undefined, types.null, types.string),
    errors: types.union(types.undefined, types.null, types.string),
    message: types.union(types.undefined, types.null, types.string),
    user: types.union(types.undefined, types.null, types.late((): any => UserModel)),
  })
  .views(self => ({
    get store() {
      return self.__getStore<RootStoreType>()
    }
  }))

export class UpdateCreditCardPayloadModelSelector extends QueryBuilder {
  get clientMutationId() { return this.__attr(`clientMutationId`) }
  get errors() { return this.__attr(`errors`) }
  get message() { return this.__attr(`message`) }
  user(builder?: string | UserModelSelector | ((selector: UserModelSelector) => UserModelSelector)) { return this.__child(`user`, UserModelSelector, builder) }
}
export function selectFromUpdateCreditCardPayload() {
  return new UpdateCreditCardPayloadModelSelector()
}

export const updateCreditCardPayloadModelPrimitives = selectFromUpdateCreditCardPayload().clientMutationId.errors.message
