/* This is a mst-gql generated file, don't modify it manually */
/* eslint-disable */
/* tslint:disable */

import { types } from "mobx-state-tree"
import { QueryBuilder } from "mst-gql"
import { ModelBase } from "./ModelBase"
import { RootStoreType } from "./index"


/**
 * UpdatePaymentMethodPayloadBase
 * auto generated base class for the model UpdatePaymentMethodPayloadModel.
 *
 * Autogenerated return type of UpdatePaymentMethod
 */
export const UpdatePaymentMethodPayloadModelBase = ModelBase
  .named('UpdatePaymentMethodPayload')
  .props({
    __typename: types.optional(types.literal("UpdatePaymentMethodPayload"), "UpdatePaymentMethodPayload"),
    /** A unique identifier for the client performing the mutation. */
    clientMutationId: types.union(types.undefined, types.null, types.string),
    message: types.union(types.undefined, types.null, types.string),
  })
  .views(self => ({
    get store() {
      return self.__getStore<RootStoreType>()
    }
  }))

export class UpdatePaymentMethodPayloadModelSelector extends QueryBuilder {
  get clientMutationId() { return this.__attr(`clientMutationId`) }
  get message() { return this.__attr(`message`) }
}
export function selectFromUpdatePaymentMethodPayload() {
  return new UpdatePaymentMethodPayloadModelSelector()
}

export const updatePaymentMethodPayloadModelPrimitives = selectFromUpdatePaymentMethodPayload().clientMutationId.message
