import { Instance } from "mobx-state-tree"
import { UpdateUserAddressPayloadModelBase } from "./UpdateUserAddressPayloadModel.base"

/* The TypeScript type of an instance of UpdateUserAddressPayloadModel */
export interface UpdateUserAddressPayloadModelType extends Instance<typeof UpdateUserAddressPayloadModel.Type> {}

/* A graphql query fragment builders for UpdateUserAddressPayloadModel */
export { selectFromUpdateUserAddressPayload, updateUserAddressPayloadModelPrimitives, UpdateUserAddressPayloadModelSelector } from "./UpdateUserAddressPayloadModel.base"

/**
 * UpdateUserAddressPayloadModel
 *
 * Autogenerated return type of UpdateUserAddress
 */
export const UpdateUserAddressPayloadModel = UpdateUserAddressPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
