import { Instance } from "mobx-state-tree"
import { UpdateUserCompanyDataPayloadModelBase } from "./UpdateUserCompanyDataPayloadModel.base"

/* The TypeScript type of an instance of UpdateUserCompanyDataPayloadModel */
export interface UpdateUserCompanyDataPayloadModelType extends Instance<typeof UpdateUserCompanyDataPayloadModel.Type> {}

/* A graphql query fragment builders for UpdateUserCompanyDataPayloadModel */
export { selectFromUpdateUserCompanyDataPayload, updateUserCompanyDataPayloadModelPrimitives, UpdateUserCompanyDataPayloadModelSelector } from "./UpdateUserCompanyDataPayloadModel.base"

/**
 * UpdateUserCompanyDataPayloadModel
 *
 * Autogenerated return type of UpdateUserCompanyData
 */
export const UpdateUserCompanyDataPayloadModel = UpdateUserCompanyDataPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
