import { Instance } from "mobx-state-tree"
import { UpdateCreditCardPayloadModelBase } from "./UpdateCreditCardPayloadModel.base"

/* The TypeScript type of an instance of UpdateCreditCardPayloadModel */
export interface UpdateCreditCardPayloadModelType extends Instance<typeof UpdateCreditCardPayloadModel.Type> {}

/* A graphql query fragment builders for UpdateCreditCardPayloadModel */
export { selectFromUpdateCreditCardPayload, updateCreditCardPayloadModelPrimitives, UpdateCreditCardPayloadModelSelector } from "./UpdateCreditCardPayloadModel.base"

/**
 * UpdateCreditCardPayloadModel
 *
 * Autogenerated return type of UpdateCreditCard
 */
export const UpdateCreditCardPayloadModel = UpdateCreditCardPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
