import { Instance } from "mobx-state-tree"
import { UpdatePaymentMethodPayloadModelBase } from "./UpdatePaymentMethodPayloadModel.base"

/* The TypeScript type of an instance of UpdatePaymentMethodPayloadModel */
export interface UpdatePaymentMethodPayloadModelType extends Instance<typeof UpdatePaymentMethodPayloadModel.Type> {}

/* A graphql query fragment builders for UpdatePaymentMethodPayloadModel */
export { selectFromUpdatePaymentMethodPayload, updatePaymentMethodPayloadModelPrimitives, UpdatePaymentMethodPayloadModelSelector } from "./UpdatePaymentMethodPayloadModel.base"

/**
 * UpdatePaymentMethodPayloadModel
 *
 * Autogenerated return type of UpdatePaymentMethod
 */
export const UpdatePaymentMethodPayloadModel = UpdatePaymentMethodPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
