import { Instance } from "mobx-state-tree"
import { UserSendPasswordResetPayloadModelBase } from "./UserSendPasswordResetPayloadModel.base"

/* The TypeScript type of an instance of UserSendPasswordResetPayloadModel */
export interface UserSendPasswordResetPayloadModelType extends Instance<typeof UserSendPasswordResetPayloadModel.Type> {}

/* A graphql query fragment builders for UserSendPasswordResetPayloadModel */
export { selectFromUserSendPasswordResetPayload, userSendPasswordResetPayloadModelPrimitives, UserSendPasswordResetPayloadModelSelector } from "./UserSendPasswordResetPayloadModel.base"

/**
 * UserSendPasswordResetPayloadModel
 *
 * Autogenerated return type of UserSendPasswordReset
 */
export const UserSendPasswordResetPayloadModel = UserSendPasswordResetPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
