/* This is a mst-gql generated file, don't modify it manually */
/* eslint-disable */
/* tslint:disable */

import { types } from "mobx-state-tree"
import { QueryBuilder } from "mst-gql"
import { ModelBase } from "./ModelBase"
import { RootStoreType } from "./index"


/**
 * UserResendConfirmationPayloadBase
 * auto generated base class for the model UserResendConfirmationPayloadModel.
 *
 * Autogenerated return type of UserResendConfirmation
 */
export const UserResendConfirmationPayloadModelBase = ModelBase
  .named('UserResendConfirmationPayload')
  .props({
    __typename: types.optional(types.literal("UserResendConfirmationPayload"), "UserResendConfirmationPayload"),
    message: types.union(types.undefined, types.string),
  })
  .views(self => ({
    get store() {
      return self.__getStore<RootStoreType>()
    }
  }))

export class UserResendConfirmationPayloadModelSelector extends QueryBuilder {
  get message() { return this.__attr(`message`) }
}
export function selectFromUserResendConfirmationPayload() {
  return new UserResendConfirmationPayloadModelSelector()
}

export const userResendConfirmationPayloadModelPrimitives = selectFromUserResendConfirmationPayload().message
