import { Instance } from "mobx-state-tree"
import { UserLogoutPayloadModelBase } from "./UserLogoutPayloadModel.base"

/* The TypeScript type of an instance of UserLogoutPayloadModel */
export interface UserLogoutPayloadModelType extends Instance<typeof UserLogoutPayloadModel.Type> {}

/* A graphql query fragment builders for UserLogoutPayloadModel */
export { selectFromUserLogoutPayload, userLogoutPayloadModelPrimitives, UserLogoutPayloadModelSelector } from "./UserLogoutPayloadModel.base"

/**
 * UserLogoutPayloadModel
 *
 * Autogenerated return type of UserLogout
 */
export const UserLogoutPayloadModel = UserLogoutPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
