import { Instance } from "mobx-state-tree"
import { UserResendConfirmationPayloadModelBase } from "./UserResendConfirmationPayloadModel.base"

/* The TypeScript type of an instance of UserResendConfirmationPayloadModel */
export interface UserResendConfirmationPayloadModelType extends Instance<typeof UserResendConfirmationPayloadModel.Type> {}

/* A graphql query fragment builders for UserResendConfirmationPayloadModel */
export { selectFromUserResendConfirmationPayload, userResendConfirmationPayloadModelPrimitives, UserResendConfirmationPayloadModelSelector } from "./UserResendConfirmationPayloadModel.base"

/**
 * UserResendConfirmationPayloadModel
 *
 * Autogenerated return type of UserResendConfirmation
 */
export const UserResendConfirmationPayloadModel = UserResendConfirmationPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
