import { Instance } from "mobx-state-tree"
import { UserUpdatePasswordWithTokenPayloadModelBase } from "./UserUpdatePasswordWithTokenPayloadModel.base"

/* The TypeScript type of an instance of UserUpdatePasswordWithTokenPayloadModel */
export interface UserUpdatePasswordWithTokenPayloadModelType extends Instance<typeof UserUpdatePasswordWithTokenPayloadModel.Type> {}

/* A graphql query fragment builders for UserUpdatePasswordWithTokenPayloadModel */
export { selectFromUserUpdatePasswordWithTokenPayload, userUpdatePasswordWithTokenPayloadModelPrimitives, UserUpdatePasswordWithTokenPayloadModelSelector } from "./UserUpdatePasswordWithTokenPayloadModel.base"

/**
 * UserUpdatePasswordWithTokenPayloadModel
 *
 * Autogenerated return type of UserUpdatePasswordWithToken
 */
export const UserUpdatePasswordWithTokenPayloadModel = UserUpdatePasswordWithTokenPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
