/* This is a mst-gql generated file, don't modify it manually */
/* eslint-disable */
/* tslint:disable */

import { types } from "mobx-state-tree"
import { QueryBuilder } from "mst-gql"
import { ModelBase } from "./ModelBase"
import { RootStoreType } from "./index"


/**
 * UserSendPasswordResetWithTokenPayloadBase
 * auto generated base class for the model UserSendPasswordResetWithTokenPayloadModel.
 *
 * Autogenerated return type of UserSendPasswordResetWithToken
 */
export const UserSendPasswordResetWithTokenPayloadModelBase = ModelBase
  .named('UserSendPasswordResetWithTokenPayload')
  .props({
    __typename: types.optional(types.literal("UserSendPasswordResetWithTokenPayload"), "UserSendPasswordResetWithTokenPayload"),
    message: types.union(types.undefined, types.string),
  })
  .views(self => ({
    get store() {
      return self.__getStore<RootStoreType>()
    }
  }))

export class UserSendPasswordResetWithTokenPayloadModelSelector extends QueryBuilder {
  get message() { return this.__attr(`message`) }
}
export function selectFromUserSendPasswordResetWithTokenPayload() {
  return new UserSendPasswordResetWithTokenPayloadModelSelector()
}

export const userSendPasswordResetWithTokenPayloadModelPrimitives = selectFromUserSendPasswordResetWithTokenPayload().message
