/* This is a mst-gql generated file, don't modify it manually */
/* eslint-disable */
/* tslint:disable */

import { types } from "mobx-state-tree"
import { QueryBuilder } from "mst-gql"
import { ModelBase } from "./ModelBase"
import { RootStoreType } from "./index"


/**
 * UserSendPasswordResetPayloadBase
 * auto generated base class for the model UserSendPasswordResetPayloadModel.
 *
 * Autogenerated return type of UserSendPasswordReset
 */
export const UserSendPasswordResetPayloadModelBase = ModelBase
  .named('UserSendPasswordResetPayload')
  .props({
    __typename: types.optional(types.literal("UserSendPasswordResetPayload"), "UserSendPasswordResetPayload"),
    message: types.union(types.undefined, types.string),
  })
  .views(self => ({
    get store() {
      return self.__getStore<RootStoreType>()
    }
  }))

export class UserSendPasswordResetPayloadModelSelector extends QueryBuilder {
  get message() { return this.__attr(`message`) }
}
export function selectFromUserSendPasswordResetPayload() {
  return new UserSendPasswordResetPayloadModelSelector()
}

export const userSendPasswordResetPayloadModelPrimitives = selectFromUserSendPasswordResetPayload().message
