/* This is a mst-gql generated file, don't modify it manually */
/* eslint-disable */
/* tslint:disable */

import { types } from "mobx-state-tree"
import { QueryBuilder } from "mst-gql"
import { ModelBase } from "./ModelBase"
import { AuthenticatableModel, AuthenticatableModelType } from "./AuthenticatableModel"
import { AuthenticatableModelSelector } from "./AuthenticatableModel.base"
import { RootStoreType } from "./index"


/**
 * UserLogoutPayloadBase
 * auto generated base class for the model UserLogoutPayloadModel.
 *
 * Autogenerated return type of UserLogout
 */
export const UserLogoutPayloadModelBase = ModelBase
  .named('UserLogoutPayload')
  .props({
    __typename: types.optional(types.literal("UserLogoutPayload"), "UserLogoutPayload"),
    authenticatable: types.union(types.undefined, types.late((): any => AuthenticatableModel)),
  })
  .views(self => ({
    get store() {
      return self.__getStore<RootStoreType>()
    }
  }))

export class UserLogoutPayloadModelSelector extends QueryBuilder {
  authenticatable(builder?: string | AuthenticatableModelSelector | ((selector: AuthenticatableModelSelector) => AuthenticatableModelSelector)) { return this.__child(`authenticatable`, AuthenticatableModelSelector, builder) }
}
export function selectFromUserLogoutPayload() {
  return new UserLogoutPayloadModelSelector()
}

export const userLogoutPayloadModelPrimitives = selectFromUserLogoutPayload()
