import { Instance } from "mobx-state-tree"
import { UserSendPasswordResetWithTokenPayloadModelBase } from "./UserSendPasswordResetWithTokenPayloadModel.base"

/* The TypeScript type of an instance of UserSendPasswordResetWithTokenPayloadModel */
export interface UserSendPasswordResetWithTokenPayloadModelType extends Instance<typeof UserSendPasswordResetWithTokenPayloadModel.Type> {}

/* A graphql query fragment builders for UserSendPasswordResetWithTokenPayloadModel */
export { selectFromUserSendPasswordResetWithTokenPayload, userSendPasswordResetWithTokenPayloadModelPrimitives, UserSendPasswordResetWithTokenPayloadModelSelector } from "./UserSendPasswordResetWithTokenPayloadModel.base"

/**
 * UserSendPasswordResetWithTokenPayloadModel
 *
 * Autogenerated return type of UserSendPasswordResetWithToken
 */
export const UserSendPasswordResetWithTokenPayloadModel = UserSendPasswordResetWithTokenPayloadModelBase
  .actions(self => ({
    // This is an auto-generated example action.
    log() {
      console.log(JSON.stringify(self))
    }
  }))
